services:
  db:
    image: mysql:8.0
    container_name: docs-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-your-secure-root-password}
      MYSQL_DATABASE: docs_db
      MYSQL_USER: docs_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-your-secure-password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - docs-network

  app:
    build: .
    container_name: docs-app
    restart: unless-stopped
    ports:
      - "3002:3000"
      - "5556:5556"
    environment:
      DATABASE_URL: mysql://docs_user:${MYSQL_PASSWORD:-your-secure-password}@db:3306/docs_db
      NEXTAUTH_URL: http://YOUR_EC2_PUBLIC_IP:3002
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-your-very-secure-secret-key-change-this}
      HOSTNAME: 0.0.0.0
      PORT: 3000
    depends_on:
      - db
    command: sh -c "npx prisma db push && ./start.sh"
    networks:
      - docs-network

volumes:
  mysql_data:

networks:
  docs-network:
    driver: bridge 