services:
  db:
    image: mysql:8.0
    container_name: docs-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: docs_db
      MYSQL_USER: docs_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-docs_password}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - docs-network

  app:
    image: ${DOCKER_IMAGE:-yourusername/docs-app:latest}
    container_name: docs-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-3002}:3000"
      - "${STUDIO_PORT:-5556}:5556"
    environment:
      DATABASE_URL: mysql://docs_user:${MYSQL_PASSWORD:-docs_password}@db:3306/docs_db
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3002}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-your-secret-key-here}
      HOSTNAME: 0.0.0.0
      PORT: 3000
    depends_on:
      - db
    command: sh -c "npx prisma db push && ./start.sh"
    networks:
      - docs-network

volumes:
  mysql_data:

networks:
  docs-network:
    driver: bridge 